// ═══ CSS ═══
import '../../css/base.css'
import '../../css/animations.css'
import '../../css/header.css'
import '../../css/slider.css'
import '../../css/popup.css'
import '../../css/content.css'
import '../../css/footer.css'
import '../../css/chatbot.css'
import '../../css/layanan-popup.css'
import '../../css/kontak.css'

// ═══ JS — urutan sama seperti HTML asli ═══
import '../../js/kontak.js'
import '../../js/store.js'
import '../../js/header.js'
import '../../js/slider.js'
import '../../js/popup.js'
import '../../js/news.js'
import '../../js/kb.js'
import '../../js/chatbot.js'
import '../../js/app.js'
import '../../js/layanan-popup.js'
